nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- API Reference:
  - base: api/module_base.md
  - enum_clients: api/module_enum_clients.md
  - run_server: api/module_run_server.md
- About:
  - License: license.md
  - Release Notes: https://github.com/jhunufernandes/sthali-core/pulls?q=is%3Apr+is%3Aclosed+release
  - Issue Tracker: https://github.com/jhunufernandes/sthali-core/issues
repo_name: sthali-core
repo_url: https://github.com/jhunufernandes/sthali-core/
site_author: '{{cookiecutter.full_name}}'
site_description: '{{cookiecutter.project_short_description}}'
site_name: sthali-core
site_url: https://jhunufernandes.github.io/sthali-core/
theme: readthedocs
