name: deploy
on:
  workflow_run:
    workflows:
      - "tests"
    branches:
      - main
    types:
      - completed
jobs:
  check-conditions:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.verify.outputs.should_deploy }}
    steps:
      - name: Verify deployment conditions
        id: verify
        env:
          TESTS_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        run: |
          if [ "$TESTS_CONCLUSION" = "success" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi
  pypi-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs:
      - check-conditions
    if: ${{ needs.check-conditions.outputs.should_deploy == 'true' }}
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"
      # - name: Upgrade pip
      #   run: |
      #     python -m pip install --upgrade pip
      - uses: ./.github/workflows/install-python-deps.yml
        with:
          extras: "stage"
      - name: Build package
        run: python -m build -o ./dist
      # - uses: pypa/gh-action-pypi-publish@release/v1
  # gh-pages-deploy:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   needs: pypi-publish
  #   steps:
  #     - name: Deploy docs
  #       run: python -m mkdocs gh-deploy -f docs/mkdocs.yml
