name: install python deps
on:
  workflow_call:
    inputs:
      extras:
        required: true
        type: string
        description: 'The "extra" dependencies to install (e.g., "docs", "stage", "tests")'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Create virtual environment
        run: |
          python -m venv ./.venv
      - name: Install dependencies
        run: |
          source ./.venv/bin/activate
          python -m pip install .[${{ inputs.extras }}]
      - uses: actions/upload-artifact@v4
        with:
          name: python-deps
          path: ./.venv
