name: run-deploy
on:
  workflow_call
jobs:
  install-deps:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/install-python-deps.yml
    with:
      extras: "stage"
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          unzip venv.zip
          .venv/bin/python -m build -o ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
  gh-pages-deploy:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          unzip venv.zip
          .venv/bin/python -m mkdocs gh-deploy -f docs/mkdocs.yml
