name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
jobs:
  detect-event-type:
    runs-on: ubuntu-latest
    outputs:
      is_push_event: ${{ steps.set-output.outputs.is_push }}
    steps:
      - name: Check event type
        id: set-output
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "is_push=true" >> $GITHUB_OUTPUT
          else
            echo "is_push=false" >> $GITHUB_OUTPUT
          fi
  run-tests:
    runs-on: ubuntu-latest
    needs:
      - detect-event-type
    steps:
      # - uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"
      # - name: Upgrade pip
      #   run: |
      #     python -m pip install --upgrade pip
      - uses: ./.github/workflows/install-python-deps.yml
        with:
          extras: ${{ needs.detect-event-type.outputs.is_push_event == 'true' && 'stage' || 'tests' }}
      - name: Run Tests
        run: |
          python -m unittest discover -v
