name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
jobs:
  detect-event-type:
    runs-on: ubuntu-latest
    outputs:
      is_push_event: ${{ steps.set-output.outputs.is_push }}
    steps:
      - id: set-output
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "is_push=true" >> $GITHUB_OUTPUT
          else
            echo "is_push=false" >> $GITHUB_OUTPUT
          fi
  install-deps:
    needs:
      - detect-event-type
    uses: ./.github/workflows/install-python-deps.yml
    with:
      extras: ${{ needs.detect-event-type.outputs.is_push_event == 'true' && 'stage' || 'tests' }}
  run-tests:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps
          path: venv.zip
      - run: |
          unzip venv.zip
          ./.venv/bin/python -m unittest discover -v
