name: deploy
on:
  workflow_run:
    workflows:
      - docs
    branches:
      - main
    types:
      - completed
jobs:
  run-deploy:
    uses: project-sthali/sthali-core/.github/workflows/run-deploy.yml@development
