name: docs
on:
  workflow_run:
    workflows:
      - tests
    branches:
      - main
    types:
      - completed
jobs:
  run-docs:
    uses: project-sthali/sthali-core/.github/workflows/run-docs.yml@development
